
package lt.viko.eif.esemasko.soap;

import jakarta.jws.*;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "MoviesPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MoviesPort {


    /**
     * @param addDirectorRequest
     * @return returns lt.viko.eif.esemasko.soap.AddDirectorResponse
     */
    @WebMethod
    @WebResult(name = "addDirectorResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addDirectorResponse")
    public AddDirectorResponse addDirector(
            @WebParam(name = "addDirectorRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addDirectorRequest")
            AddDirectorRequest addDirectorRequest);

    /**
     * @param addReviewRequest
     * @return returns lt.viko.eif.esemasko.soap.AddReviewResponse
     */
    @WebMethod
    @WebResult(name = "addReviewResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addReviewResponse")
    public AddReviewResponse addReview(
            @WebParam(name = "addReviewRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addReviewRequest")
            AddReviewRequest addReviewRequest);

    /**
     * @param changeActorRequest
     * @return returns lt.viko.eif.esemasko.soap.ChangeActorResponse
     */
    @WebMethod
    @WebResult(name = "changeActorResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "changeActorResponse")
    public ChangeActorResponse changeActor(
            @WebParam(name = "changeActorRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "changeActorRequest")
            ChangeActorRequest changeActorRequest);

    /**
     * @param getAverageRatingRequest
     * @return returns lt.viko.eif.esemasko.soap.GetAverageRatingResponse
     */
    @WebMethod
    @WebResult(name = "getAverageRatingResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getAverageRatingResponse")
    public GetAverageRatingResponse getAverageRating(
            @WebParam(name = "getAverageRatingRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getAverageRatingRequest")
            GetAverageRatingRequest getAverageRatingRequest);

    /**
     * @param deleteActorRequest
     * @return returns lt.viko.eif.esemasko.soap.DeleteActorResponse
     */
    @WebMethod
    @WebResult(name = "deleteActorResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteActorResponse")
    public DeleteActorResponse deleteActor(
            @WebParam(name = "deleteActorRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteActorRequest")
            DeleteActorRequest deleteActorRequest);

    /**
     * @param getMovieRequest
     * @return returns lt.viko.eif.esemasko.soap.GetMovieResponse
     */
    @WebMethod
    @WebResult(name = "getMovieResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getMovieResponse")
    public GetMovieResponse getMovie(
            @WebParam(name = "getMovieRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getMovieRequest")
            GetMovieRequest getMovieRequest);

    /**
     * @param addMovieRequest
     * @return returns lt.viko.eif.esemasko.soap.AddMovieResponse
     */
    @WebMethod
    @WebResult(name = "addMovieResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addMovieResponse")
    public AddMovieResponse addMovie(
            @WebParam(name = "addMovieRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addMovieRequest")
            AddMovieRequest addMovieRequest);

    /**
     * @param getMovieActorsRequest
     * @return returns lt.viko.eif.esemasko.soap.GetMovieActorsResponse
     */
    @WebMethod
    @WebResult(name = "getMovieActorsResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getMovieActorsResponse")
    public GetMovieActorsResponse getMovieActors(
            @WebParam(name = "getMovieActorsRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getMovieActorsRequest")
            GetMovieActorsRequest getMovieActorsRequest);

    /**
     * @param getMoviesByGenreRequest
     * @return returns lt.viko.eif.esemasko.soap.GetMoviesByGenreResponse
     */
    @WebMethod
    @WebResult(name = "getMoviesByGenreResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getMoviesByGenreResponse")
    public GetMoviesByGenreResponse getMoviesByGenre(
            @WebParam(name = "getMoviesByGenreRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getMoviesByGenreRequest")
            GetMoviesByGenreRequest getMoviesByGenreRequest);

    /**
     * @param getAllMoviesRequest
     * @return returns lt.viko.eif.esemasko.soap.GetAllMoviesResponse
     */
    @WebMethod
    @WebResult(name = "getAllMoviesResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getAllMoviesResponse")
    public GetAllMoviesResponse getAllMovies(
            @WebParam(name = "getAllMoviesRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getAllMoviesRequest")
            GetAllMoviesRequest getAllMoviesRequest);

}
